nginx-tcp-server 2.0 base on nginx stream module.

diff --git a/nginx-tcp/auto/lib/perl/conf b/nginx-tcp/auto/lib/perl/conf
--- a/nginx-tcp/auto/lib/perl/conf
+++ b/nginx-tcp/auto/lib/perl/conf
@@ -12,9 +12,17 @@ NGX_PERL_VER=`$NGX_PERL -v 2>&1 | grep '^This is perl' 2>&1 \
 if test -n "$NGX_PERL_VER"; then
     echo " + perl version: $NGX_PERL_VER"
 
-    if [ "`echo 'use 5.006001; print "OK"' | $NGX_PERL 2>&1`" != OK ]; then
+    if [ "`$NGX_PERL -e 'use 5.006001; print "OK"'`" != "OK" ]; then
         echo
         echo "$0: error: perl 5.6.1 or higher is required"
+        echo
+
+        exit 1;
+    fi
+
+    if [ "`$NGX_PERL -MExtUtils::Embed -e 'print "OK"'`" != "OK" ]; then
+        echo
+        echo "$0: error: perl module ExtUtils::Embed is required"
         echo
 
         exit 1;
@@ -32,6 +40,10 @@ if test -n "$NGX_PERL_VER"; then
 
     ngx_perl_ldopts=`$NGX_PERL -MExtUtils::Embed -e ldopts`
 
+    ngx_perl_dlext=`$NGX_PERL -MConfig -e 'print $Config{dlext}'`
+    ngx_perl_libdir="src/http/modules/perl/blib/arch/auto"
+    ngx_perl_module="$ngx_perl_libdir/nginx/nginx.$ngx_perl_dlext"
+
     if $NGX_PERL -V:usemultiplicity | grep define > /dev/null; then
         have=NGX_HAVE_PERL_MULTIPLICITY . auto/have
         echo " + perl interpreter multiplicity found"
@@ -42,8 +54,14 @@ if test -n "$NGX_PERL_VER"; then
         ngx_perl_ldopts=`echo $ngx_perl_ldopts | sed 's/ -pthread//'`
     fi
 
+    if [ "$NGX_SYSTEM" = "Darwin" ]; then
+        # OS X system perl wants to link universal binaries
+        ngx_perl_ldopts=`echo $ngx_perl_ldopts \
+                         | sed -e 's/-arch x86_64 -arch i386//'`
+    fi
+
     CORE_LINK="$CORE_LINK $ngx_perl_ldopts"
-    LINK_DEPS="$LINK_DEPS $NGX_OBJS/src/http/modules/perl/blib/arch/auto/nginx/nginx.so"
+    LINK_DEPS="$LINK_DEPS $NGX_OBJS/$ngx_perl_module"
 
     if test -n "$NGX_PERL_MODULES"; then
         have=NGX_PERL_MODULES value="(u_char *) \"$NGX_PERL_MODULES\""
